before:
  hooks:
  - go mod download
builds:
- id: kubegraph
  main: cmd/kubegraph/main.go
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-edge"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
release:
  github:
    owner: wwmoraes
    name: kubegraph
  prerelease: auto
