apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: my-image
    name: my-container
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
  - name: environment
    configMap:
      name: my-cm
  - name: test
    persistentVolumeClaim:
      claimName: my-pvc
  - name: environment-secrets
    secret:
      secretName: my-secret
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  my-key: my-value
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-secret
data:
  my-key: bXktdmFsdWUK
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: myhost
        port:
          number: 8080
  - match:
    - uri:
        exact: /delegate
    delegate:
      name: delegate-virtualservice
      namespace: my-ns
