apiVersion: v1
kind: Pod
metadata:
  name: a-pod
spec:
  containers:
  - image: a-image
    name: a-container
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
  - name: environment
    configMap:
      name: a-cm
  - name: test
    persistentVolumeClaim:
      claimName: a-pvc
  - name: environment-secrets
    secret:
      secretName: a-secret
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: a-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-cm
data:
  test: LOL
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: a-secret
data:
  test: TE9MCg==
