apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: my-image
    name: my-container
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
  - name: environment
    configMap:
      name: my-cm
  - name: test
    persistentVolumeClaim:
      claimName: my-pvc
  - name: environment-secrets
    secret:
      secretName: my-secret
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  my-key: my-value
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-secret
data:
  my-key: bXktdmFsdWUK
