name: Release

on:
  repository_dispatch:
    types: [release]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: set golang environment variables
      run: |
        echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
        echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
    - name: cache modules
      uses: actions/cache@v2
      with:
        path: ${GOMODCACHE}
        key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
          ${{ runner.os }}-modules-${{ env.cache-name }}-
          ${{ runner.os }}-modules-
          ${{ runner.os }}-
    - name: cache vendor
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-vendor-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-vendor-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
          ${{ runner.os }}-vendor-${{ env.cache-name }}-
          ${{ runner.os }}-vendor-
          ${{ runner.os }}-
    - name: cache build
      uses: actions/cache@v2
      with:
        path: ${HOME}/.cache/go-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: run goreleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build and publish image
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        build_args: BUILDKIT_INLINE_CACHE=1
        tags: latest
        add_git_labels: true
        cache-to: type=inline
        cache_from: type=registry,ref=${{ github.repository }}:latest
    - name: update docker hub description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        pass: ${{ secrets.DOCKER_PASSWORD }}
        description: true
